run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
  disable:
    - errcheck
    - unused
    - staticcheck
    - gosimple

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
